/*
 * This is the C++ implementation of our native methods.
 * This code will be compiled into "MathNative.dll".
 * * We must include:
 * 1. jni.h: The main JNI header file.
 * 2. MathOperations.h: A header file we will generate using 'javac -h'.
 * This file provides the exact C++ function signatures that Java expects.
 */

#include <jni.h>
#include <iostream>
#include "MathOperations.h" // This header file is auto-generated by 'javac -h'

/**
 * @brief Implementation of the native 'add' method.
 * * The function name is constructed by JNI:
 * Java_ + <PackageName_> + ClassName_ + MethodName
 * (Our class is in the default package, so PackageName is omitted).
 * * @param env JNI Environment pointer (provides JNI functions)
 * @param obj 'this' reference to the Java object
 * @param a The first jint (Java int) parameter
 * @param b The second jint (Java int) parameter
 * @return jint The result to return to Java
 */
JNIEXPORT jint JNICALL Java_MathOperations_add(JNIEnv* env, jobject obj, jint a, jint b) {
    // We can use standard C++ features, like printing to the console
    std::cout << "[C++ DLL]: Executing add(" << a << ", " << b << ")" << std::endl;
    
    // Perform the operation. jint is compatible with int.
    jint result = a + b;
    
    // Return the result
    return result;
}

/**
 * @brief Implementation of the native 'subtract' method.
 */
JNIEXPORT jint JNICALL Java_MathOperations_subtract(JNIEnv* env, jobject obj, jint a, jint b) {
    std::cout << "[C++ DLL]: Executing subtract(" << a << ", " << b << ")" << std::endl;
    
    jint result = a - b;
    
    return result;
}